version: '3.8'

services:
  vault:
    image: vault:latest
    container_name: vault
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    expose:
      - 8200
    ports:
      - "8200:8200"

  supersecret:
    build: ./
    container_name: supersecret
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS: ":8082"
    ports:
      - "8082:8082"
    depends_on:
      - vault