version: '3.8'

services:
  vault:
    image: vault:latest
    container_name: vault
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
    expose:
      - 8200
    restart: unless-stopped
    command: vault server -config=/vault/config/vault.json

  supersecret:
    #    build: ./
    image: ghcr.io/dreikomag/sup3rs3cretmes5age:main
    container_name: supersecret
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
      SUPERSECRETMESSAGE_HTTP_BINDING_ADDRESS: ":8082"
    ports:
      - "8082:8082"
    depends_on:
      - vault
    restart: unless-stopped